"""交付引擎：Gate2 产物校验 + ZIP 打包 + Evidence Pack。

产物结构（对齐 MVP 交付包）：
    output/projects/{full}-{version}/
      ├── src/{full}/...                 生成的 Addon 源码
      ├── DEPLOY.md / README.md          文档（简版）
      └── evidence/
          ├── change_spec.json
          ├── manifest.json
          ├── conflict_report.json
          └── gate2_report.json
    output/projects/{full}-{version}/{full}-{version}.zip   交付 ZIP
"""

from __future__ import annotations

import io
import json
import os
import zipfile
from datetime import datetime
from typing import Optional

from shared import errors
from shared.result import Result

# Gate2：每个 Addon 必须存在的关键产物（相对 src/{full}/src/{ns}/{fn}/）
_REQUIRED_SUFFIXES = [
    "configure.zcml",
    "setuphandlers.py",
    "profiles/default/metadata.xml",
    "profiles/default/registry.xml",
    "behaviors/configure.zcml",
    "extender/configure.zcml",
]


def _output_base() -> str:
    # __file__ = backend/engines/delivery/package_export.py
    # dirname×4 → aiconfigtool/ 根目录
    root = os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    )
    return os.path.join(root, "output", "projects")


class DeliveryEngine:
    def __init__(self, output_base: Optional[str] = None) -> None:
        self._base = output_base or _output_base()

    def deliver(
        self,
        full_name: str,
        version: str,
        files: dict,
        change_spec: dict,
        conflict_report: dict,
    ) -> Result:
        # ── Gate2：产物完整性 ──
        gate2 = self._gate2(full_name, files)
        if not gate2["passed"]:
            return Result.failure(
                "Gate2 产物校验失败：%s" % "; ".join(gate2["missing"]),
                code=errors.GENERATION_FAILED,
                details=gate2,
            )

        pkg_id = "%s-%s" % (full_name, version)
        proj_dir = os.path.join(self._base, pkg_id)
        os.makedirs(proj_dir, exist_ok=True)

        # ── 落盘源码 ──
        for rel, content in files.items():
            path = os.path.join(proj_dir, rel.replace("/", os.sep))
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="\n") as h:
                h.write(content)

        # ── 文档 ──
        deploy_md = self._deploy_md(full_name, version, change_spec)
        readme_md = "# %s\n\nGenerated by AiConfigTool.\n" % full_name
        self._write(proj_dir, "实施部署指南.md", deploy_md)
        self._write(proj_dir, "README.md", readme_md)

        # ── Evidence Pack ──
        ev_dir = os.path.join(proj_dir, "evidence")
        os.makedirs(ev_dir, exist_ok=True)
        manifest = {
            "addon": full_name,
            "version": version,
            "generatedAt": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "fileCount": len(files),
            "changeCount": len(change_spec.get("changes", [])),
            "siteCode": change_spec.get("siteCode", ""),
            "companyCode": change_spec.get("companyCode", ""),
            "gate2": gate2,
        }
        self._write_json(ev_dir, "manifest.json", manifest)
        self._write_json(ev_dir, "change_spec.json", change_spec)
        self._write_json(ev_dir, "conflict_report.json", conflict_report)
        self._write_json(ev_dir, "gate2_report.json", gate2)

        # ── ZIP 打包 ──
        zip_name = "%s.zip" % pkg_id
        zip_path = os.path.join(proj_dir, zip_name)
        self._zip(zip_path, files, deploy_md, readme_md, manifest, change_spec)
        size_kb = max(1, os.path.getsize(zip_path) // 1024)

        return Result.success(
            {
                "packageId": pkg_id,
                "fullName": full_name,
                "version": version,
                "zipName": zip_name,
                "packageSizeKb": size_kb,
                "fileCount": len(files),
                "gate2": gate2,
                "deployDocName": "实施部署指南.md",
            }
        )

    # ── Gate2 ──
    def _gate2(self, full_name: str, files: dict) -> dict:
        ns, fn = full_name.split(".", 1)
        prefix = "src/%s/src/%s/%s/" % (full_name, ns, fn)
        missing = [
            suffix
            for suffix in _REQUIRED_SUFFIXES
            if (prefix + suffix) not in files
        ]
        # 至少要有一个字段实现文件（behavior 或 extender）
        has_impl = any(
            ("/behaviors/" in k or "/extender/" in k)
            and k.endswith(".py")
            and not k.endswith("__init__.py")
            for k in files
        )
        has_permission_rules = False
        for path, content in files.items():
            if not path.endswith("profiles/default/registry.xml"):
                continue
            if "permission_rules" in content and '"rules":[{' in content.replace(" ", ""):
                has_permission_rules = True
                break
        if not has_impl:
            if not has_permission_rules:
                missing.append("字段实现文件（behavior/extender .py）或权限规则")
        return {
            "gate": "Gate2",
            "passed": len(missing) == 0,
            "missing": missing,
            "checkedCount": len(_REQUIRED_SUFFIXES) + 1,
        }

    # ── 打包 ──
    def _zip(self, zip_path, files, deploy_md, readme_md, manifest, change_spec):
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            for rel, content in files.items():
                zf.writestr(rel, content)
            zf.writestr("实施部署指南.md", deploy_md)
            zf.writestr("README.md", readme_md)
            zf.writestr("evidence/manifest.json",
                        json.dumps(manifest, ensure_ascii=False, indent=2))
            zf.writestr("evidence/change_spec.json",
                        json.dumps(change_spec, ensure_ascii=False, indent=2))
        with open(zip_path, "wb") as h:
            h.write(buf.getvalue())

    # ── 文档 ──
    def _deploy_md(self, full_name: str, version: str, change_spec: dict, site: dict | None = None) -> str:
        container = (site or {}).get("connection", {}).get("containerName", "senaite")
        url = (site or {}).get("url", "")
        lines = [
            "# %s 实施部署指南" % full_name,
            "",
            "## 1. 基本信息",
            "",
            "| 项目 | 信息 |",
            "|------|------|",
            "| Addon | `%s` |" % full_name,
            "| 版本 | `%s` |" % version,
            "| 目标站点 | `%s` |" % (url or change_spec.get("siteCode", "")),
            "| 生成时间 | %s |" % datetime.now().strftime("%Y-%m-%d %H:%M"),
            "",
            "## 2. 变更内容",
            "",
        ]
        for c in change_spec.get("changes", []):
            lines.append("- **%s**：%s" % (c.get("changeType"), c.get("description", "")))

        lines += [
            "",
            "## 3. 自动安装（需 Docker）",
            "",
            "AiConfigTool 已内置自动安装流程：",
            "",
            "1. 将源码复制到 `addons/customers/%s/`" % full_name,
            "2. 更新 `custom-addon.cfg`（develop + eggs + zcml）",
            "3. 容器内执行 `buildout`（网络失败自动重试 3 次）",
            "4. `docker restart %s` 重启 LIMS 服务" % container,
            "5. HTTP POST `%s/install_products` 自动安装" % url,
            "6. 摸底扫描验证字段是否生效",
            "",
            "> 以上步骤在 Addon 工坊点击「安装并验证」即可自动完成。",
            "",
            "## 4. 手动安装（非 Docker / 远程服务器）",
            "",
            "```bash",
            "# 1. 解压 ZIP 包",
            "unzip %s-%s.zip" % (full_name, version),
            "# 2. 将解压出的 src/%s/ 目录放到 Senaite 实例的 addons 目录" % full_name,
            "cp -r src/%s /path/to/senaitelims/addons/" % full_name,
            "# 3. 修改 buildout.cfg，在 [buildout] 段添加：",
            "#    develop += /path/to/addons/%s" % full_name,
            "#    eggs += %s" % full_name,
            "# 4. 运行 buildout",
            "$ bin/buildout",
            "# 5. 重启 LIMS 服务",
            "$ docker compose restart",
            "# 6. 浏览器打开 Site Setup → Add-ons，勾选安装 %s" % full_name,
            "```",
            "",
            "## 5. 验证清单",
            "",
        ]
        for c in change_spec.get("changes", []):
            if c.get("changeType") == "AddField":
                lines.append("- [ ] 在 **%s** 的编辑页面能看到新增字段 `%s`" % (c.get("typeId"), c.get("fieldName")))
            elif c.get("changeType") == "UpdatePermission":
                verb = "具备" if (c.get("permissionAction") or "grant") in ("grant", "create") else "不再具备"
                target = c.get("targetType") or c.get("permissionId") or ""
                lines.append("- [ ] 角色 **%s** 已%s **%s** 的相关权限" % (c.get("roleName"), verb, target))
        lines += ["- [ ] Addon 在 Add-ons 列表中显示为已安装", "- [ ] 现有功能不受影响", ""]
        return "\n".join(lines)

    # ── 辅助 ──
    def _write(self, base, name, content):
        with open(os.path.join(base, name), "w", encoding="utf-8", newline="\n") as h:
            h.write(content)

    def _write_json(self, base, name, obj):
        with open(os.path.join(base, name), "w", encoding="utf-8") as h:
            json.dump(obj, h, ensure_ascii=False, indent=2)
