services:
  app:
    image: maitux/senaite:latest
    container_name: senaite-source-clean-2x
    restart: unless-stopped
    ports:
      - 9001:8080
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024MB
    volumes:
      - ./data:/data
    environment:
      SITE: senaite
      PASSWORD: changeme
      PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
      PIP_TRUSTED_HOST: pypi.tuna.tsinghua.edu.cn
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      PYTHONIOENCODING: utf-8
      CHAMELEON_CACHE: /data/cache
