services:
  zeo:
    image: maitux/senaite:latest
    container_name: senaite-source-clean-2x-zeo
    command: zeo
    volumes:
      - ./data:/data

  instance:
    image: maitux/senaite:latest
    container_name: senaite-source-clean-2x
    ports:
      - 8080:8080
    depends_on:
      - zeo
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024MB
    environment:
      ZEO_ADDRESS: "zeo:8080"
    volumes:
      - ./data:/data
