"""AddField 生成引擎：change_spec + 摸底 → 完整 Senaite Addon 文件树。

严格移植 MVP 已验证的产物结构（Client.medai_remark 真实交付包）：
  - Archetypes 目标 → extender/ SchemaExtender + adapter zcml + registry extender_gates
  - Dexterity 目标 → behaviors/ behavior schema + plone:behavior zcml + registry behavior_mappings
  - 固定骨架：setup.py / configure.zcml / setuphandlers.py / browser / profiles

产出 dict: { 相对路径: 文件内容 }，路径以 src/{full_name}/ 为根（与交付 ZIP 一致）。
"""

from __future__ import annotations

import json
import re
from typing import Optional

from shared import errors
from shared.result import Result

# 字段类型白名单（移植 _supported_field_type_keys_v01）
_ARCHETYPES_TYPES = {"textline", "textarea"}
_DEXTERITY_TYPES = {"textline", "textarea", "integer", "number", "bool", "date", "datetime"}

# fieldType（change_spec）→ 归一 key
_TYPE_ALIASES = {
    "stringfield": "textline",
    "textline": "textline",
    "string": "textline",
    "textfield": "textarea",
    "text": "textarea",
    "textarea": "textarea",
    "integerfield": "integer",
    "int": "integer",
    "integer": "integer",
    "floatfield": "number",
    "float": "number",
    "number": "number",
    "booleanfield": "bool",
    "bool": "bool",
    "boolean": "bool",
    "date": "date",
    "datetime": "datetime",
}

# Dexterity: 归一 key → zope.schema 类型
_DEXTERITY_SCHEMA = {
    "textline": "schema.TextLine",
    "textarea": "schema.Text",
    "integer": "schema.Int",
    "number": "schema.Float",
    "bool": "schema.Bool",
    "date": "schema.Date",
    "datetime": "schema.Datetime",
}


def _norm_type(field_type: str) -> str:
    return _TYPE_ALIASES.get((field_type or "").strip().lower(), (field_type or "").strip().lower())


def _camel(s: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in re.split(r"[_\W]+", s) if p)


def _u(text) -> str:
    """Python2 兼容的 unicode 字面量表达式。"""
    return "u" + json.dumps(text if text is not None else "", ensure_ascii=False)


class AddonGenerator:
    def __init__(self, meta: dict, changes: list[dict], summary: dict) -> None:
        self.namespace = meta["namespace"]
        self.function = meta["functionName"]
        self.full = "%s.%s" % (self.namespace, self.function)
        self.version = meta.get("version", "0.1.0")
        self.description = meta.get("description", "Generated by AiConfigTool")
        self.changes = changes
        self.types = (summary or {}).get("types") or {}

    # ── 入口 ──
    def generate(self) -> Result:
        add_fields = [c for c in self.changes if c.get("changeType") == "AddField"]
        if not add_fields:
            return Result.failure(
                "没有可生成的 AddField 变更", code=errors.GENERATION_FAILED
            )

        files: dict[str, str] = {}
        self._emit_scaffold(files)

        behavior_regs: list[tuple[str, str, str]] = []  # (type_id, provides, title)
        extender_gates: list[tuple[str, str]] = []  # (type_id, field_name)
        behavior_zcml: list[str] = []
        adapter_zcml: list[str] = []

        for change in add_fields:
            r = self._emit_one_field(files, change, behavior_zcml, adapter_zcml,
                                     behavior_regs, extender_gates)
            if r.is_failure():
                return r

        # 汇总 behaviors/configure.zcml 与 extender/configure.zcml
        files[self._p("behaviors/configure.zcml")] = self._behaviors_configure(behavior_zcml)
        files[self._p("extender/configure.zcml")] = self._extender_configure(adapter_zcml)
        # registry.xml（含 behavior_mappings + extender_gates）
        files[self._p("profiles/default/registry.xml")] = self._registry_xml(
            behavior_regs, extender_gates
        )
        return Result.success({"fullName": self.full, "version": self.version, "files": files})

    # ── 单字段分派 ──
    def _emit_one_field(self, files, change, behavior_zcml, adapter_zcml,
                        behavior_regs, extender_gates) -> Result:
        type_id = change.get("typeId")
        field_name = change.get("fieldName")
        field_type = change.get("fieldType", "StringField")
        required = bool(change.get("required"))
        title = change.get("description") or field_name

        norm = _norm_type(field_type)
        framework = (self.types.get(type_id) or {}).get("framework") or change.get("framework") or "unknown"
        if framework == "unknown":
            # 无法判定框架时，默认按 dexterity（Senaite 2.x 新类型多为 dexterity）
            framework = "dexterity"

        field_spec = {"field_type": norm, "title": title, "required": required}

        if framework == "archetypes":
            if norm not in _ARCHETYPES_TYPES:
                return Result.failure(
                    "Archetypes 类型 %s 暂不支持字段类型 %s（支持 textline/textarea）"
                    % (type_id, field_type),
                    code=errors.GENERATION_FAILED,
                )
            self._emit_archetypes(files, type_id, field_name, field_spec, adapter_zcml)
            extender_gates.append((type_id, field_name))
        else:
            if norm not in _DEXTERITY_TYPES:
                return Result.failure(
                    "Dexterity 类型 %s 暂不支持字段类型 %s" % (type_id, field_type),
                    code=errors.GENERATION_FAILED,
                )
            provides = self._emit_dexterity(files, type_id, field_name, field_spec, behavior_zcml)
            behavior_regs.append((type_id, provides, "%s %s" % (type_id, field_name)))
        return Result.success(None)

    # ── Dexterity behavior ──
    def _emit_dexterity(self, files, type_id, field_name, field_spec, behavior_zcml) -> str:
        module = "%s_%s" % (type_id.lower(), field_name.lower())
        interface = "I%s%s" % (_camel(type_id), _camel(field_name))
        schema_type = _DEXTERITY_SCHEMA[field_spec["field_type"]]
        field_var = re.sub(r"\W", "_", field_name)

        desc_expr = ""
        body = (
            "# -*- coding: utf-8 -*-\n"
            "from plone.autoform.interfaces import IFormFieldProvider\n"
            "from plone.supermodel import model\n"
            "from zope import schema\n"
            "from zope.interface import provider\n\n\n"
            "@provider(IFormFieldProvider)\n"
            "class %s(model.Schema):\n"
            "    %s = %s(title=%s, required=%s%s)\n"
        ) % (
            interface, field_var, schema_type,
            _u(field_spec["title"]), "True" if field_spec["required"] else "False", desc_expr,
        )
        files[self._p("behaviors/%s.py" % module)] = body

        provides = "%s.behaviors.%s.%s" % (self.full, module, interface)
        behavior_zcml.append(
            '  <plone:behavior\n      title=%s\n      provides=%s />\n'
            % (json.dumps("%s %s" % (type_id, field_name), ensure_ascii=False),
               json.dumps(provides, ensure_ascii=False))
        )
        return provides

    # ── Archetypes extender ──
    def _emit_archetypes(self, files, type_id, field_name, field_spec, adapter_zcml) -> None:
        module = "%s_%s" % (type_id.lower(), field_name.lower())
        class_name = "%s%sExtender" % (_camel(type_id), _camel(field_name))
        is_text = field_spec["field_type"] == "textarea"
        ext_field = "ExtensionTextField" if is_text else "ExtensionStringField"
        widget = "TextAreaWidget" if is_text else "StringWidget"
        gate_key = "%s.%s" % (type_id, field_name)

        body = (
            "# -*- coding: utf-8 -*-\n"
            "from Products.Archetypes.interfaces import IBaseObject\n"
            "from Products.Archetypes.public import StringField\n"
            "from Products.Archetypes.public import StringWidget\n"
            "from Products.Archetypes.public import TextAreaWidget\n"
            "from Products.Archetypes.public import TextField\n"
            "from archetypes.schemaextender.field import ExtensionField\n"
            "from archetypes.schemaextender.interfaces import ISchemaExtender\n"
            "from %s.setuphandlers import resolve_extender_site_gate\n"
            "from zope.component import adapts\n"
            "from zope.interface import implementer\n\n\n"
            "TARGET_SCOPE = u\"site\"\n"
            "GATE_KEY = %s\n\n"
            "class ExtensionStringField(ExtensionField, StringField):\n    pass\n\n\n"
            "class ExtensionTextField(ExtensionField, TextField):\n    pass\n\n\n"
            "@implementer(ISchemaExtender)\n"
            "class %s(object):\n"
            "    adapts(IBaseObject)\n\n"
            "    _portal_type = %s\n\n"
            "    fields = (\n"
            "        %s(\n"
            "            %s,\n"
            "            default=u\"\",\n"
            "            required=%s,\n"
            "            schemata=\"default\",\n"
            "            widget=%s(\n"
            "                label=%s,\n"
            "                description=u\"Generated by %s (SchemaExtender).\",\n"
            "            ),\n"
            "        ),\n"
            "    )\n\n"
            "    def __init__(self, context):\n        self.context = context\n\n"
            "    def getFields(self):\n"
            "        if getattr(self.context, \"portal_type\", None) != self._portal_type:\n"
            "            return []\n"
            "        gate = resolve_extender_site_gate(self.context, gate_id=GATE_KEY, target_scope=TARGET_SCOPE)\n"
            "        if not gate.get(\"allowed\"):\n            return []\n"
            "        return list(self.fields)\n"
        ) % (
            self.full, _u(gate_key), class_name, _u(type_id), ext_field,
            _u(field_name), "True" if field_spec["required"] else "False",
            widget, _u(field_spec["title"]), self.full,
        )
        files[self._p("extender/%s.py" % module)] = body

        factory = "%s.extender.%s.%s" % (self.full, module, class_name)
        adapter_zcml.append(
            '  <adapter\n      factory=%s\n      name=%s />\n'
            % (json.dumps(factory, ensure_ascii=False), json.dumps(module, ensure_ascii=False))
        )

    # ── 固定骨架 ──
    def _emit_scaffold(self, files: dict) -> None:
        ns, fn, full = self.namespace, self.function, self.full
        files["src/%s/setup.py" % full] = self._setup_py()
        files["src/%s/README.rst" % full] = "%s\n%s\n\nGenerated addon by AiConfigTool.\n" % (
            full, "=" * len(full)
        )
        files["src/%s/src/%s/__init__.py" % (full, ns)] = (
            '__import__("pkg_resources").declare_namespace(__name__)\n'
        )
        files[self._p("__init__.py")] = (
            "import logging\n\nlogger = logging.getLogger('%s')\n" % full
        )
        files[self._p("configure.zcml")] = self._root_configure()
        files[self._p("setuphandlers.py")] = _SETUPHANDLERS.replace("__FULL__", full)
        files[self._p("behaviors/__init__.py")] = ""
        files[self._p("extender/__init__.py")] = ""
        files[self._p("browser/__init__.py")] = ""
        files[self._p("browser/configure.zcml")] = (
            '<configure\n    xmlns="http://namespaces.zope.org/zope">\n</configure>\n'
        )
        files[self._p("browser/viewlets.py")] = _VIEWLETS.replace("__FULL__", full)
        files[self._p("profiles/default/metadata.xml")] = (
            '<?xml version="1.0"?>\n<metadata>\n  <version>1000</version>\n</metadata>\n'
        )
        files[self._p("profiles/default/import_steps.xml")] = (
            '<?xml version="1.0"?>\n<import-steps>\n'
            '  <import-step\n      id=\'%s.various\'\n      version="1000"\n'
            '      title=\'%s\'\n      handler=\'%s.setuphandlers.import_various\'>\n'
            '    <dependency name="plone.app.registry" />\n  </import-step>\n</import-steps>\n'
            % (full, full, full)
        )
        files[self._p("profiles/default/%s.txt" % full)] = ""
        # 卸载 profile
        files[self._p("profiles/uninstall/import_steps.xml")] = (
            '<?xml version="1.0"?>\n<import-steps>\n'
            '  <import-step\n      id=\'%s.uninstall\'\n      version="1000"\n'
            '      title=\'%s uninstall\'\n'
            '      handler=\'%s.setuphandlers.post_uninstall\'>\n'
            '    <dependency name="plone.app.registry" />\n  </import-step>\n</import-steps>\n'
            % (full, full, full)
        )
        files[self._p("profiles/uninstall/%s_uninstall.txt" % full)] = ""

    # ── 路径辅助：python 包内路径 ──
    def _p(self, rel: str) -> str:
        return "src/%s/src/%s/%s/%s" % (self.full, self.namespace, self.function, rel)

    def _setup_py(self) -> str:
        return (
            "import os\nfrom setuptools import find_packages, setup\n\n\n"
            "setup(\n"
            "    name='%s',\n    version=\"%s\",\n"
            "    description=%s,\n"
            "    long_description=open(\"README.rst\").read() if os.path.exists(\"README.rst\") else \"\",\n"
            "    author=\"Maitux Team\",\n    author_email=\"dev@maitux.com\",\n"
            "    url='https://github.com/maitux/%s',\n"
            "    packages=find_packages(\"src\"),\n    package_dir={\"\": \"src\"},\n"
            "    namespace_packages=['%s'],\n    include_package_data=True,\n    zip_safe=False,\n"
            "    install_requires=[\"setuptools\"],\n"
            "    entry_points=\"\"\"\n    [z3c.autoinclude.plugin]\n    target = plone\n    \"\"\",\n)\n"
            % (self.full, self.version, json.dumps(self.description, ensure_ascii=False),
               self.full, self.namespace)
        )

    def _root_configure(self) -> str:
        return (
            '<configure\n    xmlns="http://namespaces.zope.org/zope"\n'
            '    xmlns:five="http://namespaces.zope.org/five"\n'
            '    xmlns:genericsetup="http://namespaces.zope.org/genericsetup"\n'
            '    xmlns:plone="http://namespaces.plone.org/plone"\n'
            "    i18n_domain='%s'>\n\n"
            '  <include package="Products.Five" />\n'
            '  <include package="Products.GenericSetup" file="meta.zcml" />\n'
            '  <include package="plone.behavior" file="meta.zcml" />\n'
            '  <five:registerPackage package="." />\n\n'
            '  <genericsetup:registerProfile\n      name="default"\n      title=\'%s\'\n'
            '      directory="profiles/default"\n'
            '      description="Generated addon for AiConfigTool apply output"\n'
            "      post_handler='%s.setuphandlers.post_install'\n"
            '      provides="Products.GenericSetup.interfaces.EXTENSION"\n      />\n\n'
            '  <genericsetup:registerProfile\n      name="uninstall"\n'
            "      title='%s (uninstall)'\n"
            '      directory="profiles/uninstall"\n'
            "      post_handler='%s.setuphandlers.post_uninstall'\n"
            '      provides="Products.GenericSetup.interfaces.EXTENSION"\n      />\n\n'
            '  <include package=".behaviors" />\n'
            '  <include package=".extender" />\n'
            '  <include package=".browser" />\n</configure>\n'
            % (self.full, self.full, self.full, self.full, self.full)
        )

    def _behaviors_configure(self, blocks: list[str]) -> str:
        inner = "\n".join(blocks)
        return (
            '<configure\n    xmlns="http://namespaces.zope.org/zope"\n'
            '    xmlns:plone="http://namespaces.plone.org/plone">\n%s</configure>\n'
            % (("\n" + inner + "\n") if inner else "")
        )

    def _extender_configure(self, blocks: list[str]) -> str:
        inner = "\n".join(blocks)
        return (
            '<configure\n    xmlns="http://namespaces.zope.org/zope">\n%s</configure>\n'
            % (("\n" + inner + "\n") if inner else "")
        )

    def _registry_xml(self, behavior_regs, extender_gates) -> str:
        mappings: dict[str, list] = {}
        for type_id, provides, _title in behavior_regs:
            mappings.setdefault(type_id, []).append(provides)
        behavior_value = json.dumps(
            {"meta": {"target_scope": "site", "site_id": None}, "mappings": mappings},
            ensure_ascii=False, separators=(",", ":"),
        )
        gates = {"%s.%s" % (t, f): {"target_scope": "site", "site_id": None}
                 for t, f in extender_gates}
        gates_value = json.dumps(gates, ensure_ascii=False, separators=(",", ":"))

        def record(name, title, value):
            return (
                "  <record name='%s.%s'>\n"
                '    <field type="plone.registry.field.Text">\n'
                "      <title>%s</title>\n"
                "      <description>JSON</description>\n      <default />\n    </field>\n"
                "    <value>%s</value>\n  </record>\n"
                % (self.full, name, title, value)
            )

        return (
            '<?xml version="1.0"?>\n<registry>\n'
            + record("behavior_mappings", "Behavior mappings (JSON)", behavior_value)
            + record("extender_gates", "SchemaExtender site gates (JSON)", gates_value)
            + record("listing_patches", "Listing patches (JSON)", "{}")
            + record("template_assets", "Template assets (JSON)", "{}")
            + "</registry>\n"
        )


# 固定文件（移植 MVP，__FULL__ 占位替换为包全名）
_SETUPHANDLERS = r'''import json

from __FULL__ import logger

try:
    from zope.component.hooks import getSite
except Exception:
    def getSite():
        return None


def _safe_text(value):
    if value is None:
        return ""
    if isinstance(value, bytes):
        try:
            return value.decode("utf-8")
        except Exception:
            return ""
    return str(value)


def _get_registry():
    try:
        from zope.component import getUtility
        from plone.registry.interfaces import IRegistry
        return getUtility(IRegistry)
    except Exception:
        return None


def _get_portal(context=None):
    obj = context
    for _ in range(32):
        if obj is None:
            break
        if getattr(obj, 'portal_setup', None) is not None:
            return obj
        obj = getattr(obj, 'aq_parent', None)
    return getSite()


def _registry_json(key):
    reg = _get_registry()
    if reg is None:
        return {}
    raw = ''
    try:
        raw = reg.get(key, '')
    except Exception:
        try:
            raw = reg.records[key].value
        except Exception:
            raw = ''
    text = _safe_text(raw).strip()
    if not text:
        return {}
    try:
        data = json.loads(text)
    except Exception:
        return {}
    return data if isinstance(data, dict) else {}


def resolve_extender_site_gate(context, gate_id=None, target_scope='site'):
    scope = _safe_text(target_scope).strip().lower() or 'site'
    portal = _get_portal(context)
    current_site_id = ''
    if portal is not None:
        try:
            current_site_id = _safe_text(portal.getId()).strip()
        except Exception:
            current_site_id = ''
    gates = _registry_json('__FULL__.extender_gates')
    gate_meta = gates.get(gate_id) if isinstance(gates, dict) and gate_id else {}
    if not isinstance(gate_meta, dict):
        gate_meta = {}
    expected_scope = _safe_text(gate_meta.get('target_scope') or scope).strip().lower() or scope
    expected_site_id = _safe_text(gate_meta.get('site_id')).strip() or None
    allowed = True
    if expected_scope == 'site' and expected_site_id:
        allowed = current_site_id == expected_site_id
    return {
        'allowed': bool(allowed),
        'target_scope': expected_scope,
        'expected_site_id': expected_site_id,
        'current_site_id': current_site_id or None,
        'gate_id': gate_id,
    }


def import_various(context):
    if context is not None:
        marker = getattr(context, 'readDataFile', lambda *args, **kwargs: None)('__FULL__.txt')
        if marker is None:
            return
    try:
        from __FULL__.browser.viewlets import apply_listing_patches
        portal = context.getSite() if context is not None and hasattr(context, 'getSite') else getSite()
        apply_listing_patches(portal)
    except Exception:
        logger.exception('Failed to apply listing patches during import')


def post_install(portal_setup):
    logger.info('__FULL__ post-install')


def post_uninstall(portal_setup):
    logger.info('__FULL__ post-uninstall')
'''

_VIEWLETS = r'''import json


def _get_registry():
    try:
        from zope.component import getUtility
        from plone.registry.interfaces import IRegistry
        return getUtility(IRegistry)
    except Exception:
        return None


def _registry_json(key):
    reg = _get_registry()
    if reg is None:
        return {}
    raw = ''
    try:
        raw = reg.get(key, '')
    except Exception:
        try:
            raw = reg.records[key].value
        except Exception:
            raw = ''
    if isinstance(raw, bytes):
        try:
            raw = raw.decode('utf-8')
        except Exception:
            raw = ''
    raw = str(raw or '').strip()
    if not raw:
        return {}
    try:
        data = json.loads(raw)
    except Exception:
        return {}
    return data if isinstance(data, dict) else {}


def apply_listing_patches(portal=None):
    patches = _registry_json('__FULL__.listing_patches')
    changed = False
    for view_class, meta in patches.items():
        if not isinstance(view_class, str) or '.' not in view_class:
            continue
        try:
            mod_name, cls_name = view_class.rsplit('.', 1)
            mod = __import__(mod_name, fromlist=[cls_name])
            view_cls = getattr(mod, cls_name)
        except Exception:
            continue
        current = getattr(view_cls, 'columns', None) or {}
        if not isinstance(current, dict):
            current = {}
        patched = dict(current)
        columns = meta.get('columns') if isinstance(meta, dict) else []
        for item in columns if isinstance(columns, list) else []:
            if not isinstance(item, dict):
                continue
            column_id = str(item.get('column_id') or '').strip()
            if not column_id:
                continue
            entry = patched.get(column_id)
            if not isinstance(entry, dict):
                entry = {}
            entry.setdefault('title', item.get('title') or column_id)
            entry['toggle'] = bool(item.get('toggle')) if item.get('toggle') is not None else True
            patched[column_id] = entry
        view_cls.columns = patched
        changed = True
    return changed
'''
