"""错误码常量与 HTTP 状态映射（对齐技术设计文档 7.3）。

集中定义，避免错误码字符串散落在各 handler 里。
"""

from __future__ import annotations

# ── 错误码 ──
VALIDATION_ERROR = "VALIDATION_ERROR"
SITE_CONNECTION_FAILED = "SITE_CONNECTION_FAILED"
INVENTORY_STALE = "INVENTORY_STALE"
NAMESPACE_CONFLICT = "NAMESPACE_CONFLICT"
CHANGE_SPEC_INVALID = "CHANGE_SPEC_INVALID"
GENERATION_FAILED = "GENERATION_FAILED"
NOT_FOUND = "NOT_FOUND"
INTERNAL_ERROR = "INTERNAL_ERROR"

# ── 错误码 → HTTP 状态码 ──
STATUS_BY_CODE = {
    VALIDATION_ERROR: 400,
    SITE_CONNECTION_FAILED: 400,
    INVENTORY_STALE: 400,
    CHANGE_SPEC_INVALID: 400,
    NAMESPACE_CONFLICT: 409,
    NOT_FOUND: 404,
    GENERATION_FAILED: 500,
    INTERNAL_ERROR: 500,
}


def http_status_for(code: str) -> int:
    """未登记的错误码默认 500。"""
    return STATUS_BY_CODE.get(code, 500)
